### ISSUE TITLE
Errors in Home Assistant log since 2024.6.X

### ISSUE THREAD

**Issue by pyrodex** [dahlb/ha_hatch#143]
I am seeing the following errors after the HA 2024.6 upgrade:

```
2024-06-16 09:24:56.676 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'ha_hatch' at custom_components/ha_hatch/__init__.py, line 77: _, mqtt_connection, rest_devices, expiration_time = await get_rest_devices( (offender: /usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py, line 1696: with open(path, 'rb') as stream:), please create a bug report at https://github.com/dahlb/ha_hatch/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_hatch/__init__.py", line 105, in async_setup_entry
    await setup_connection("initial setup")
  File "/config/custom_components/ha_hatch/__init__.py", line 77, in setup_connection
    _, mqtt_connection, rest_devices, expiration_time = await get_rest_devices(
```

I am seeing sporadic issues but wanted to report the issues.

**Comment by dahlb** [comment]
fixed in [1.20.4](https://github.com/dahlb/ha_hatch/commit/e63b5cb368b858c92a989d80c09bfffb59366673) improves event thread performance and prevents this warning message
