### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by mjakeseaton** [dahlb/ha_hatch#20]
I've been using this integration for about a week with no issues, but yesterday, it began to fail. I can't recall the timing of when I began to see the error and when I upgraded to HA Core 2022.10

```
Error setting up entry _XXXXXXXX@XXXX.com_ for ha_hatch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_hatch/__init__.py", line 65, in async_setup_entry
    _lazy_install()
  File "/config/custom_components/ha_hatch/__init__.py", line 54, in _lazy_install
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for ha_hatch not found: ['hatch-rest-api==1.13.2'].
```

I tried rerunning the integration and am receiving a 500.

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 822, in async_create_flow
    flow = handler()
  File "/config/custom_components/ha_hatch/config_flow.py", line 68, in __init__
    _lazy_install()
  File "/config/custom_components/ha_hatch/__init__.py", line 54, in _lazy_install
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for ha_hatch not found: ['hatch-rest-api==1.13.2'].
```

**Comment by Intecpsp** [comment]
Same here

**Comment by dahlb** [comment]
I'm having the same issue, I opened a ticket with the repo that created our work around https://github.com/qqaatw/aws-crt-python-musllinux/issues/1  Looking into other solutions while I wait to hear back from them

**Comment by dahlb** [comment]
v1.9.1 released with custom work around derived from qqaatw's work around, it takes a few minutes to finish installing but does like the old manual scripts did but automatically.  It over uses the ui thread so be patient on first start as it will appear to be unresponsive for a few minutes while the dependencies are installed.

**Comment by mjakeseaton** [comment]
Thanks Brendan. That seemed to do the trick!
