### ISSUE TITLE
ERROR: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Intecpsp** [dahlb/ha_hatch#22]
I don't remember the timeline here, but I think I started to get this after updating Core to 2022.10.3 or OS to 9.2

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_hatch/__init__.py", line 83, in async_setup_entry
    _lazy_install()
  File "/config/custom_components/ha_hatch/__init__.py", line 67, in _lazy_install
    _install_alpine_dependencies()
  File "/config/custom_components/ha_hatch/__init__.py", line 57, in _install_alpine_dependencies
    _LOGGER.error(
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by dahlb** [comment]
I expect this is resolved with version 1.9.3 I just released
