### ISSUE TITLE
Component assumes that if it's running in Docker it is using Alpine

### ISSUE THREAD

**Issue by bmcclure** [dahlb/ha_hatch#39]
When I try and work on this component locally in Docker, I'm running into the problem of the _lazy_install() function assuming that all installations in Docker are running on Alpine Linux.

Running HA inside an Ubuntu container and attempting to install the component gives the following result:

```
Config flow could not be loaded: 500 Internal Server Error Traceback (most recent call last): File "/home/vscode/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware return await handler(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle result = await result File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 148, in post return await super().post(request) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post result = await self._flow_mgr.async_init( File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/config_entries.py", line 831, in async_init flow, result = await task File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/config_entries.py", line 849, in _async_init flow = await self.async_create_flow(handler, context=context, data=data) File "/home/vscode/.local/lib/python3.10/site-packages/homeassistant/config_entries.py", line 973, in async_create_flow flow = handler() File "/workspaces/ha_hatch/custom_components/ha_hatch/config_flow.py", line 68, in __init__ _lazy_install() File "/workspaces/ha_hatch/custom_components/ha_hatch/__init__.py", line 74, in _lazy_install _install_alpine_dependencies() File "/workspaces/ha_hatch/custom_components/ha_hatch/__init__.py", line 58, in _install_alpine_dependencies with Popen( File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'apk'
```

What it seems to boil down to is that it's unable to find the "apk" command and fully errors out as a result.

I will probably create a PR shortly once I find the right fix, but just wanted to post about the issue in the meantime.

**Comment by dahlb** [comment]
the way I do it is doing intelliJ with simple docker-compose.yml

```
version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /Users/dahlb/Desktop/ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123

```

it uses the official docker image just fine.

**Comment by bmcclure** [comment]
I think that seems good in general, but with how the component assumes that any Docker container must be running on Alpine, it means nobody running HA in a different type of Docker container would be able to configure the component.

If the component needs to keep the code that runs the apk command, would it make sense to depend on the "distro" library and check if it's running in alpine first?

**Comment by bmcclure** [comment]
I think this should be good to go now that Debian and Ubuntu support are added. Thank you!
