### ISSUE TITLE
automatic alpine dependency installation

### ISSUE THREAD

**Issue by dahlb** [dahlb/ha_hatch#8]
port automated installation of dependency to simplify the setup for alpine/haos users based on 

https://github.com/qqaatw/JciHitachiHA/blob/2326c87d32abb96e885e4bbd982cd9364843a47b/custom_components/jcihitachi_tw/__init__.py#L29-L34

**Comment by dahlb** [comment]
@qqaatw is looks like the wheels you make are not compatible with the homeassistant docker image? or am I not locking a version or something else I don't understand?

```
/config # pip install awscrt -f https://qqaatw.github.io/aws-crt-python-musllinux/
Looking in links: https://qqaatw.github.io/aws-crt-python-musllinux/
Collecting awscrt
  Using cached awscrt-0.14.6.tar.gz (21.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: awscrt
  Building wheel for awscrt (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/_test.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/auth.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/checksums.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/common.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/crypto.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/http.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/io.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/s3.py -> build/lib.linux-x86_64-cpython-310/awscrt
      creating build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 348, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 266, in run
          self._build_dependency(lib, dep_build_dir, dep_install_path)
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 259, in _build_dependency
          self._build_dependency_impl(aws_lib, build_dir, install_path)
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 157, in _build_dependency_impl
          cmake = get_cmake_path()
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 113, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt
  Running setup.py clean for awscrt
Failed to build awscrt
Installing collected packages: awscrt
  Running setup.py install for awscrt ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for awscrt did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/_test.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/auth.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/checksums.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/common.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/crypto.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/http.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/io.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/s3.py -> build/lib.linux-x86_64-cpython-310/awscrt
      creating build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 348, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 690, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 266, in run
          self._build_dependency(lib, dep_build_dir, dep_install_path)
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 259, in _build_dependency
          self._build_dependency_impl(aws_lib, build_dir, install_path)
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 157, in _build_dependency_impl
          cmake = get_cmake_path()
        File "/tmp/pip-install-u8v94pxz/awscrt_e450c979856745abac83889f402db2e7/setup.py", line 113, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> awscrt

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by dahlb** [comment]
developing https://github.com/dahlb/ha_hatch/pull/9

**Comment by qqaatw** [comment]
What's the platform that you were using to install awscrt? The repository currently only provides wheels for `i686`, `x86_64`, and `aarch64`.

**Comment by dahlb** [comment]
it's a synology with an intel x86_64, I'm still new to python but comparing the logs from the install with the packages listed at https://qqaatw.github.io/aws-crt-python-musllinux/ my guess is a difference in python interpreter? the only difference seems to be cp310 vs cpython310
```
linux-x86_64-cpython-310
```

```
awscrt-0.14.6-cp310-cp310-linux_x86_64.whl
```

from the docker attempting to install, I grabbed from info that might help
python -VV
```
Python 3.10.5 (main, Jun 22 2022, 13:51:01) [GCC 11.2.1 20220219]
```

cat /etc/*-release
```
3.16.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.0
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

uname -mrs
```
Linux 4.4.180+ x86_64
```

**Comment by dahlb** [comment]
well that guess was wrong, did the pip with -vvv and got 
```
Fetching project page and analyzing links: https://qqaatw.github.io/aws-crt-python-musllinux/
Getting page https://qqaatw.github.io/aws-crt-python-musllinux/
Starting new HTTPS connection (1): qqaatw.github.io:443
https://qqaatw.github.io:443 "GET /aws-crt-python-musllinux/ HTTP/1.1" 301 162
Starting new HTTP connection (1): qqaatw.dev:80
http://qqaatw.dev:80 "GET /aws-crt-python-musllinux/ HTTP/1.1" 301 None
Starting new HTTPS connection (1): qqaatw.dev:443
https://qqaatw.dev:443 "GET /aws-crt-python-musllinux/ HTTP/1.1" 503 None
Could not fetch URL https://qqaatw.github.io/aws-crt-python-musllinux/: HTTPSConnectionPool(host='qqaatw.dev', port=443): Max retries exceeded with url: /aws-crt-python-musllinux/ (Caused by ResponseError('too many 503 error responses')) - skipping
Fetching project page and analyzing links: https://pypi.org/simple/pip/
```

and 
pip debug --verbose
```
  cp310-cp310-musllinux_1_2_x86_64
  cp310-cp310-musllinux_1_1_x86_64
  cp310-cp310-musllinux_1_0_x86_64
  cp310-cp310-linux_x86_64
```
confirming there are packages that are compatible but the repo is returning a 503 to pip

**Comment by qqaatw** [comment]
Hi, thanks for the info. I've disabled the CDN proxy for the awscrt repo. Feel free to try again.

**Comment by dahlb** [comment]
@qqaatw that worked great, thanks for all your help with this wheels issue

**Comment by qqaatw** [comment]
Glad to help. We're on the same boat.
